on: 
  push:
    branches:
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore .
      - name: Build
        run: dotnet publish ./src/ATIL.FeeCalculator.csproj --configuration Release --no-restore -o publish
      - name: checkout octopus
        uses: OctopusDeploy/install-octopus-cli-action@v3.1.3
      - name: Create zip package  
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          base_path: infrastructure
          output_folder: ./infra
          package_id: atil_feecalculator-infrastructure
          version: "1.0.${{github.run_number}}-beta"
      - name: Push packages  
        uses: OctopusDeploy/push-package-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          space: 'Default'
          packages: |
            infra/atil_feecalculator-infrastructure.$MY_VAR.zip
            out/atil_feecalculator.$MY_VAR.zip
      - name: Create release  
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: "ATIL - Fee Calculator API"
          release_number: "1.0.${{github.run_number}}-beta"
          channel: Dev