on: 
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore .
      - name: Build
        run: dotnet publish --configuration Release --no-restore -o publish
      - name: checkout octopus
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      - name: pack & push to octo 
        run: |
          MY_VAR="1.0.${{github.run_number}}"
          octo pack --basePath=publish --id atil_feecalculator --version $MY_VAR --outFolder ./out --format zip
          octo push --package "./out/atil_feecalculator.${MY_VAR}.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"
          octo create-release --project="ATIL - Fee Calculator API" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}" --channel=Prod --version=$MY_VAR

